name: CI Practice

on: 
  push:
   
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub repository
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 on run.py
        run: |
          flake8 run.py
